Repository Capstone2-team4/LogIT_BE, pull requests merged in 2025-06, with the labels that each got.

#63 pr Feat/#60 코드블럭 관련 api 구현 엔티티 구조 수정
  src/main/java/LogITBackend/LogIT/DTO/CodeBlockListResponse.java
  src/main/java/LogITBackend/LogIT/DTO/CodeRequestDTO.java
  src/main/java/LogITBackend/LogIT/DTO/CodeResponseDTO.java
  src/main/java/LogITBackend/LogIT/DTO/CommitCodeBlocksRequest.java
  src/main/java/LogITBackend/LogIT/DTO/CommitCodeBlocksResponse.java
  src/main/java/LogITBackend/LogIT/DTO/SnippetUpdateRequest.java
  src/main/java/LogITBackend/LogIT/DTO/SnippetUpdateResponse.java
  src/main/java/LogITBackend/LogIT/apiPayload/code/status/ErrorStatus.java
  src/main/java/LogITBackend/LogIT/config/RedisConfig.java
  src/main/java/LogITBackend/LogIT/controller/CategoryController.java
  src/main/java/LogITBackend/LogIT/controller/CodeController.java
  src/main/java/LogITBackend/LogIT/controller/GithubController.java
  src/main/java/LogITBackend/LogIT/domain/CodeCategories.java
  src/main/java/LogITBackend/LogIT/domain/Codes.java
  src/main/java/LogITBackend/LogIT/domain/Commit.java
  src/main/java/LogITBackend/LogIT/domain/File.java
  src/main/java/LogITBackend/LogIT/domain/Users.java
  src/main/java/LogITBackend/LogIT/domain/common/RedisCommon.java
  src/main/java/LogITBackend/LogIT/repository/CodesRepository.java
  src/main/java/LogITBackend/LogIT/service/CodeService.java
  src/main/java/LogITBackend/LogIT/service/CodeServiceImpl.java
Labels: ✨ Feature

#65 [Feat] 플러그인 API 개발: 에러 정보, 에러코드, 에러 해결 코드 저장 API 구현
  src/main/java/LogITBackend/LogIT/DTO/ErrorRequestDTO.java
  src/main/java/LogITBackend/LogIT/DTO/ErrorResponseDTO.java
  src/main/java/LogITBackend/LogIT/LogItApplication.java
  src/main/java/LogITBackend/LogIT/controller/ErrorController.java
  src/main/java/LogITBackend/LogIT/domain/ErrorCode.java
  src/main/java/LogITBackend/LogIT/domain/ErrorInfo.java
  src/main/java/LogITBackend/LogIT/domain/ErrorSolvedCode.java
  src/main/java/LogITBackend/LogIT/repository/ErrorCodeRepository.java
  src/main/java/LogITBackend/LogIT/repository/ErrorInfoRepository.java
  src/main/java/LogITBackend/LogIT/repository/ErrorSolvedCodeRepository.java
  src/main/java/LogITBackend/LogIT/service/ErrorCommandService.java
  src/main/java/LogITBackend/LogIT/service/ErrorCommandServiceImpl.java
  src/main/java/LogITBackend/LogIT/service/ErrorQueryService.java
  src/main/java/LogITBackend/LogIT/service/ErrorQueryServiceImpl.java
Labels: ✨ Feature

#69 [Feat] 에러 리스트 조회 시 에러 아이디 반환 기능 추가
  src/main/java/LogITBackend/LogIT/DTO/ErrorResponseDTO.java
  src/main/java/LogITBackend/LogIT/converter/ErrorConverter.java
  src/main/java/LogITBackend/LogIT/domain/ErrorCode.java
  src/main/java/LogITBackend/LogIT/domain/ErrorInfo.java
  src/main/java/LogITBackend/LogIT/domain/ErrorSolvedCode.java
Labels: ✨ Feature

#71 [Refactor] 에러 리스트 조회, 에러 코드 리스트 조회, 에러 해결 코드 리스트 조회 API의 request를 query string에서 path variable로 변경
  src/main/java/LogITBackend/LogIT/controller/ErrorController.java
Labels: 🔨 Refactor

#75 [Refactor] 플러그인 API: 에러, 에러코드, 에러해결 코드 저장 API 수정: 여러 에러 저장 가능하도록 수정
  src/main/java/LogITBackend/LogIT/DTO/ErrorRequestDTO.java
  src/main/java/LogITBackend/LogIT/controller/ErrorController.java
  src/main/java/LogITBackend/LogIT/service/ErrorCommandService.java
  src/main/java/LogITBackend/LogIT/service/ErrorCommandServiceImpl.java
Labels: 🔨 Refactor

#78 pr commit 당시 전체 코드 조회 기능 구현
  src/main/java/LogITBackend/LogIT/DTO/CodeResponseDTO.java
  src/main/java/LogITBackend/LogIT/DTO/FileResponseDTO.java
  src/main/java/LogITBackend/LogIT/apiPayload/code/status/ErrorStatus.java
  src/main/java/LogITBackend/LogIT/controller/GithubController.java
  src/main/java/LogITBackend/LogIT/service/CodeServiceImpl.java
  src/main/java/LogITBackend/LogIT/service/GithubService.java
  src/main/java/LogITBackend/LogIT/service/GithubServiceImpl.java
Labels: ✨ Feature

#79 pr Feat/#77 커밋 당시 전체 코드 조회 기능 구현
  src/main/java/LogITBackend/LogIT/controller/GithubController.java
  src/main/java/LogITBackend/LogIT/service/GithubServiceImpl.java
Labels: 🐞 BugFix

#80 [Feat] ai 글요약 기능(commits에 대한) 구현 완료
  src/main/java/LogITBackend/LogIT/DTO/Chatgpt/AiSummaryRequestDTO.java
  src/main/java/LogITBackend/LogIT/DTO/Chatgpt/AiSummaryResponseDTO.java
  src/main/java/LogITBackend/LogIT/DTO/Chatgpt/ChatGPTRequestDTO.java
  src/main/java/LogITBackend/LogIT/DTO/Chatgpt/ChatGPTResponseDTO.java
  src/main/java/LogITBackend/LogIT/DTO/Chatgpt/MessageDTO.java
  src/main/java/LogITBackend/LogIT/config/OpenAiConfig.java
  src/main/java/LogITBackend/LogIT/controller/AiSummaryController.java
  src/main/java/LogITBackend/LogIT/service/AiSummaryCommandService.java
  src/main/java/LogITBackend/LogIT/service/AiSummaryCommandServiceImpl.java
Labels: ✨ Feature

#82 pr commit event 발생시 redis clear 코드 수정
  src/main/java/LogITBackend/LogIT/service/CodeServiceImpl.java
Labels: 🐞 BugFix

#88 [Feat] 플러그인 API 수정: 에러, 에러코드, 에러해결코드 저장 API
  src/main/java/LogITBackend/LogIT/DTO/ErrorRequestDTO.java
  src/main/java/LogITBackend/LogIT/domain/ErrorCodeBlock.java
  src/main/java/LogITBackend/LogIT/repository/ErrorCodeBlockRepository.java
  src/main/java/LogITBackend/LogIT/service/ErrorCommandServiceImpl.java
Labels: ✨ Feature

#99 [Feat] ai요약시 코드블럭과 에러내용 추가
  src/main/java/LogITBackend/LogIT/repository/CodesRepository.java
  src/main/java/LogITBackend/LogIT/service/AiSummaryCommandServiceImpl.java
Labels: ✨ Feature
